[msg CoffeePrompt]
[f 0 5 -258][f 2 1]> You're tired from entering the TV...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> By drinking coffee, you should have the energy
[n]to do something else before the night ends.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Pour yourself some coffee?[n][f 1 1][e]

[msg NoLongerTired]
[f 0 5 -258][f 2 1]> ...!?[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Any fatigue you felt earlier has gone![n][f 1 1][e]

[msg CoffeeTutorial]
[f 0 5 -258][f 2 1]You can now use the [f 2 5 3 -1 0] Dojima
[n]gave you to make yourself a hot drink from
[n]the kitchen.[f 1 1][e]
[f 0 5 -258][f 2 1]Coffee will remove exhaustion and allow
[n]you to go out at night, even after venturing
[n]into the TV world.[f 1 1][e]

[msg MSG_1ST_NIGHTSTREET_MORO2]
[f 0 5 -258][f 2 1]> ......[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Morooka has summoned you...[n][f 1 1][e]

[msg MSG_DOUJIMA_COMINGHOME_03 [Dojima]]
[f 0 5 -258][f 2 1][f 4 6 11 1 0 1][f 3 1 3 0 6 730]You're home. So, what was it?[n][f 1 1][e]
[f 0 5 -258][f 2 1]Huh? You were given a school jersey?[n]That's it?[n][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 11 4 0 1]He could've just given you that at[n]school...[n][f 1 1][e]
[f 0 5 -258][f 2 1]...Well, I'm sure telling you that isn't[n]helping. School's tough enough as it is.[n][f 1 1][e]
[f 0 5 -258][f 2 1]With these incidents going on, everyone's[n]on edge...[n][f 1 1][e]