[msg HANG_OUT_MSG]
[f 0 5 -258][f 2 1]Who do you want to see?[n][f 1 1][e]

[msg ADACHI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Adachi is nearby.[n][f 1 1][e]

[msg AI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Ai is nearby.[n][f 1 1][e]

[msg CHIE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Chie is nearby.[n][f 1 1][e]

[msg DOJIMA_ALREADY_HERE]
[f 0 5 -258][f 2 1]Dojima is nearby.[n][f 1 1][e]

[msg AYANE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Ayane is nearby.[n][f 1 1][e]

[msg YUMI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Yumi is nearby.[n][f 1 1][e]

[msg BUS_ALREADY_HERE]
[f 0 5 -258][f 2 1]The bus stop is nearby.[n][f 1 1][e]

[msg HISANO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Hisano is nearby.[n][f 1 1][e]

[msg KANJI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Kanji is nearby.[n][f 1 1][e]

[msg MARIE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Marie is nearby.[n][f 1 1][e]

[msg NANAKO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Nanako is nearby.[n][f 1 1][e]

[msg NAOKI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Naoki is nearby.[n][f 1 1][e]

[msg NAOTO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Naoto is nearby.[n][f 1 1][e]

[msg RISE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Rise is nearby.[n][f 1 1][e]

[msg KOU_ALREADY_HERE]
[f 0 5 -258][f 2 1]Kou is nearby.[n][f 1 1][e]

[msg DAISUKE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Daisuke is nearby.[n][f 1 1][e]

[msg YOSUKE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Yosuke is nearby.[n][f 1 1][e]

[msg YUKIKO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Yukiko is nearby.[n][f 1 1][e]

[msg SHRINE_ALREADY_HERE]
[f 0 5 -258][f 2 1]The shrine is nearby.[n][f 1 1][e]
