[sel QUIZ_1]
[f 0 5 -258][f 2 1]"Group A."[e]
[f 0 5 -258][f 2 1]"Group B."[e]
[f 0 5 -258][f 2 1]"Can you repeat that?"[e]

[sel QUIZ_2_0]
[f 0 5 -258][f 2 1]"Group A."[e]
[f 0 5 -258][f 2 1]"Group B."[e]
[f 0 5 -258][f 2 1]"Can you repeat that?"[e]

[sel QUIZ_2_1]
[f 0 5 -258][f 2 1]"Group A!"[e]
[f 0 5 -258][f 2 1]"Group B!"[e]
[f 0 5 -258][f 2 1]"Can you repeat that?!"[e]

[sel QUIZ_3 ]
[f 0 5 -258][f 2 1]"A group."[e]
[f 0 5 -258][f 2 1]"B group."[e]
[f 0 5 -258][f 2 1]"Can you repeat that?"[e]

[msg MSG_NPC_07_QUEST04_0_FIRST [Funky student]]
[f 0 5 -258][f 2 1]Then it's time for another logical[n]throwdown! Once again, the category is[n]categories.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Our old friends group A and B are back[n]in effect.[n][f 1 1][e]

[msg MSG_NPC_07_QUEST04_0_REST [Funky student]]
[f 0 5 -258][f 2 1]F's in group A,[n]G's in group B.[n][f 1 1][e]
[f 0 5 -258][f 2 1]N is in group A,[n]O is in group B.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Which group does "P" have detailed onto[n]the side of his ride?[n][f 1 1][e]

[msg MSG_NPC_07_QUEST04_3_FIRST [Funky student]]
[f 0 5 -258][f 2 1]All right, now for the next problem![n]Next one's another group riddle, baby.[n][f 1 1][e]

[msg MSG_NPC_07_QUEST04_3_REST [Funky student]]
[f 0 5 -258][f 2 1]Tc is group A.[n]Xe is group B.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Md is group A.[n]Rn is group B.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Bk is group A.[n]Ne is group B.[n][f 1 1][e]
[f 0 5 -258][f 2 1]Which of these three is in group A's[n]speed dial?[n][f 1 1][e]

[sel QUIZ_3_1 ]
[f 0 5 -258][f 2 1]"Yttrium."[e]
[f 0 5 -258][f 2 1]"Argon."[e]
[f 0 5 -258][f 2 1]"Promethium."[e]
[f 0 5 -258][f 2 1]"Can you repeat that?"[e]

[sel QUIZ_3_2]
[f 0 5 -258][f 2 1]"Onset."[e]
[f 0 5 -258][f 2 1]"Need."[e]
[f 0 5 -258][f 2 1]"Decimal."[e]
[f 0 5 -258][f 2 1]"Can you repeat that?"[e]

[msg MSG_NPC_07_QUEST04_4_FIRST [Funky student]]
[f 0 5 -258][f 2 1]It is now time for me to spit the final verse![n]This time it's a "find the mismatch" problem![n][f 1 1][e]
[f 0 5 -258][f 2 1]It took me a long time to come up with[n]this one! Which one of these things is[n]not like the others?[n][f 1 1][e]

[msg MSG_NPC_07_QUEST04_4_REST [Funky student]]
[f 0 5 -258][f 2 1]Stop, need, decimal, arts,[n]penal, wines, onset, guns...[n][f 1 1][e]
[f 0 5 -258][f 2 1]Which one of these should find a[n]different circle of friends?[n][f 1 1][e]
