[msg READ_MORE]
[f 0 5 -258][f 2 1]> Because you have read "Hyperspeed[n]Reading," not as much time has passed[n]as you had expected.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You decided to continue reading.[n]Which book will you read?[n][f 1 1][e]

[msg CANT_READ_MORE]
[f 0 5 -258][f 2 1]> Because you have read "Hyperspeed[n]Reading," not as much time has passed[n]as you had expected.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> However, you have already finished reading all[n]the books you have...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You may wish to return here once you[n]find something new to read.[n][f 1 1][e]
