[msg YukikoTravelAvailable]
[s]¡Viaje rápido a el Castillo[n]de Yukiko desbloqueado![n][w][e]

[msg KanjiTravelAvailable]
[s]¡Viaje rápido a los[n]Baños públicos desbloqueado![n][w][e]

[msg RiseTravelAvailable]
[s]¡Viaje rápido a Striptease[n]Marukyu desbloqueado![n][w][e]

[msg MitsuoTravelAvailable]
[s]¡Viaje rápido a Void Quest[n]desbloqueado![n][w][e]

[msg NaotoTravelAvailable]
[s]¡Viaje rápido al Laboratorio[n]secreto desbloqueado![n][w][e]

[msg NanakoTravelAvailable]
[s]¡Viaje rápido al[n]Cielo desbloqueado![n][w][e]

[msg AdachiTravelAvailable]
[s]¡Viaje rápido a Magatsu[n]Inaba desbloqueado![n][w][e]