[sel OptionSel]
[f 0 5 -258][f 2 1]Añadir miembro[e]
[f 0 5 -258][f 2 1]Quitar miembro[e]
[f 0 5 -258][f 2 1]Terminar[e]

[msg ConfirmPartyRise [Rise]]
[f 0 5 -258][f 2 1]¿Confirmar cambios y[n]regresar a la entrada del piso?[e]

[msg SelectMemberMsg]
[f 0 5 -258][f 2 1]¿Añadir cual miembro?[e]

[msg SelectMemberMsgRise [Rise]]
[f 0 5 -258][f 2 1]¿Añadir cual miembro?[e]

[msg ReplaceMemberMsg]
[f 0 5 -258][f 2 1]¿Remplazar cual miembro?[e]

[msg ReplaceMemberMsgRise [Rise]]
[f 0 5 -258][f 2 1]¿Remplazar cual miembro?[e]

[msg RemoveMemberMsg]
[f 0 5 -258][f 2 1]¿Quitar cual miembro?[e]

[msg RemoveMemberMsgRise [Rise]]
[f 0 5 -258][f 2 1]¿Quitar cual miembro?[e]

[msg OptionMsg]
[f 0 5 -258][f 2 1]¿Qué vas a hacer?[e]

[msg OptionMsgRise [Rise]]
[f 0 5 -258][f 2 1]¿Qué vas a hacer?[e]

[sel TOMB_SEL_HOOK]
[f 0 5 -258][f 2 1]Volver a la entrada[e]
[f 0 5 -258][f 2 1]Organizar grupo[e]
[f 0 5 -258][f 2 1]Daidara[e]
[f 0 5 -258][f 2 1]Shiroku[e]
[f 0 5 -258][f 2 1]Habitación Terciopelo[e]
[f 0 5 -258][f 2 1]Volver a casa[e]
[f 0 5 -258][f 2 1]Guardar[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[sel LIQUEUR_SEL_HOOK]
[f 0 5 -258][f 2 1]Volver a la entrada[e]
[f 0 5 -258][f 2 1]Organizar grupo[e]
[f 0 5 -258][f 2 1]Guardar[e]
[f 0 5 -258][f 2 1]Cancelar[e]