[msg DEATH_BOX]
[f 0 5 65278][f 2 1]> You sense an intensely terrifying[n]presence...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> Open this chest?[n][f 1 1][e]

[msg DEATH_ENCOUNT]
[f 0 5 65278][f 2 1]> Something jumped out of the chest![n][f 1 1][e]

[msg LOCK_BOX]
[f 0 5 65278][f 2 1]> The treasure chest is locked...[n][f 1 1][e]

[msg USE_MUGI_OK]
[f 0 5 65278][f 2 1]> Open the treasure chest with Crack Wheat?[n]    (Crack Wheat remaining: [f 0 1 1][f 2 4 0][f 0 1 0])[n][f 1 1][e]

[msg USE_KEY_OK]
[f 0 5 65278][f 2 1]> Open the treasure chest with a key?[n]    (Chest Keys remaining: [f 0 1 1][f 2 4 0][f 0 1 0])[n][f 1 1][e]

[msg TRAPBOX_ENCOUNT]
[f 0 5 65278][f 2 1]> A Shadow jumped out of the chest![n][f 1 1][e]

[msg HELP_STAIR_KUMA [Teddie]]
[f 0 5 65278][f 2 1]We found the stairs![n][f 1 1][e]
[f 0 5 65278][f 2 1]I can lead you there anytime![n][f 1 1][e]

[msg FIND_BOX_YOSUKE_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 374]Ooh. We found a chest![n][f 1 6 65535][e]

[msg FIND_BOX_YOSUKE_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 374]Ooh. We found a chest![n][f 1 6 65535][e]

[msg FIND_STAIR_YOSUKE_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 381]We found the stairs![n]Let's move on![n][f 1 6 65535][e]

[msg FIND_ENEMY_YOSUKE_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 378]We found a Shadow![n][f 1 6 65535][e]

[msg FIND_KANJI_YOSUKE_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 441]Ooh, we found a punk![n][f 1 6 65535][e]

[msg FIND_BOX_CHIE_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 383]Oh, a treasure chest![n][f 1 6 65535][e]

[msg FIND_STAIR_CHIE_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 389]We found the stairs![n][f 1 6 65535][e]

[msg FIND_STAIR_CHIE_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 390]We found the stairs! Let's[n]hurry to the next floor.[n][f 1 6 65535][e]

[msg FIND_BOX_YUKIKO_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 392]Oh, we found a[n]treasure chest![n][f 1 6 65535][e]

[msg FIND_STAIR_YUKIKO_03]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 400]We found the stairway.[n]Shall we go on?[n][f 1 6 65535][e]

[msg FIND_ENEMY_YUKIKO_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 396]We found a Shadow![n]Are you ready?[n][f 1 6 65535][e]

[msg FIND_BOX_KANJI_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 411]We found a treasure chest![n][f 1 6 65535][e]

[msg FIND_BOX_KANJI_03]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 412]Hey, we found a chest.[n]Let's pop this sucker open![n][f 1 6 65535][e]

[msg FIND_ENEMY_KANJI_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 413]We found a Shadow![n]Let's crush it![n][f 1 6 65535][e]

[msg FIND_BOX_KUMA_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 428]Wooo, we found a chest![n][f 1 6 65535][e]

[msg FIND_STAIR_KUMA_03]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 436]We found the stairs![n][f 1 6 65535][e]

[msg FIND_ENEMY_KUMA_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 431]We found the enemy![n]Be careful![n][f 1 6 65535][e]

[msg FIND_ENEMY_KUMA_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 432]Shadows![n]Let's get 'em![n][f 1 6 65535][e]

[msg FIND_ENEMY_KUMA_03]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 432]We found a Shadow![n]I'll take'em on![n][f 1 6 65535][e]

[msg FIND_PLAYER_KUMA_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 535]Huh? We found you![n][f 1 6 65535][e]

[msg FIND_BOX_RISE_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 401]We found a chest![n][f 1 6 65535][e]

[msg FIND_KUMA_RISE_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 490]Ooh, we found Teddie![n][f 1 6 65535][e]

[msg FIND_BOX_NAOTO_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 420]We found a treasure chest![n][f 1 6 65535][e]

[msg FIND_STAIR_NAOTO_03]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 427]We found the stairs![n][f 1 6 65535][e]