[msg HANG_OUT_MSG]
[f 0 5 -258][f 2 1]¿A quién te gustaría ver?[n][f 1 1][e]

[msg ADACHI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Adachi está cerca.[n][f 1 1][e]

[msg AI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Ai está cerca.[n][f 1 1][e]

[msg CHIE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Chie está cerca.[n][f 1 1][e]

[msg DOJIMA_ALREADY_HERE]
[f 0 5 -258][f 2 1]Dojima está cerca.[n][f 1 1][e]

[msg AYANE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Ayane está cerca.[n][f 1 1][e]

[msg YUMI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Yumi está cerca.[n][f 1 1][e]

[msg BUS_ALREADY_HERE]
[f 0 5 -258][f 2 1]La parada de autobús está cerca.[n][f 1 1][e]

[msg HISANO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Hisano está cerca.[n][f 1 1][e]

[msg KANJI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Kanji está cerca.[n][f 1 1][e]

[msg MARIE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Marie está cerca.[n][f 1 1][e]

[msg NANAKO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Nanako está cerca.[n][f 1 1][e]

[msg NAOKI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Naoki está cerca.[n][f 1 1][e]

[msg NAOTO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Naoto está cerca.[n][f 1 1][e]

[msg RISE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Rise está cerca.[n][f 1 1][e]

[msg KOU_ALREADY_HERE]
[f 0 5 -258][f 2 1]Kou está cerca.[n][f 1 1][e]

[msg DAISUKE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Daisuke está cerca.[n][f 1 1][e]

[msg YOSUKE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Yosuke está cerca.[n][f 1 1][e]

[msg YUKIKO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Yukiko está cerca.[n][f 1 1][e]

[msg SHRINE_ALREADY_HERE]
[f 0 5 -258][f 2 1]El santuario está cerca.[n][f 1 1][e]
