[msg School_Text]
[f 0 5 -258][f 2 1]Instituto Yasogami[n][f 1 1][e]

[sel School]
[f 0 5 -258][f 2 1]Edificio de aulas[e]
[f 0 5 -258][f 2 1]Edificio de prácticas[e]
[f 0 5 -258][f 2 1]Edificio de prácticas, P1[e]
[f 0 5 -258][f 2 1]Edificio de prácticas, P2[e]
[f 0 5 -258][f 2 1]Aula 2-2[e]
[f 0 5 -258][f 2 1]Ir al pueblo[e]
[f 0 5 -258][f 2 1]Ver calendario[e]
[f 0 5 -258][f 2 1]Pasar tiempo con...[e]
[f 0 5 -258][f 2 1]Guardar[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[sel ClassroomBuilding]
[f 0 5 -258][f 2 1]Edificio de aulas, P1[e]
[f 0 5 -258][f 2 1]Edificio de aulas, P2[e]
[f 0 5 -258][f 2 1]Edificio de aulas, P3[e]
[f 0 5 -258][f 2 1]Azotea[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[sel PracticeBuilding]
[f 0 5 -258][f 2 1]Edificio de prácticas, P1[e]
[f 0 5 -258][f 2 1]Edificio de prácticas, P2[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[msg Street_Text]
[f 0 5 -258][f 2 1]Pueblo de Inaba[n][f 1 1][e]

[sel Street]
[f 0 5 -258][f 2 1]Calle comercial[e]
[f 0 5 -258][f 2 1]Calle comercial, Sur[e]
[f 0 5 -258][f 2 1]Calle comercial, Norte[e]
[f 0 5 -258][f 2 1]Santuario[e]
[f 0 5 -258][f 2 1]Salir de la Calle comercial[e]
[f 0 5 -258][f 2 1]Ver calendario[e]
[f 0 5 -258][f 2 1]Pasar tiempo con...[e]
[f 0 5 -258][f 2 1]Guardar[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[sel ShoppingDistrictDay]
[f 0 5 -258][f 2 1]Calle comercial, Sur[e]
[f 0 5 -258][f 2 1]Calle comercial, Norte[e]
[f 0 5 -258][f 2 1]Armería[e]
[f 0 5 -258][f 2 1]Shiroku[e]
[f 0 5 -258][f 2 1]Habitación Terciopelo[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[sel StreetNight]
[f 0 5 -258][f 2 1]Calle comercial[e]
[f 0 5 -258][f 2 1]Santuario[e]
[f 0 5 -258][f 2 1]Ribera del río[e]
[f 0 5 -258][f 2 1]Volver a casa[e]
[f 0 5 -258][f 2 1]Ver calendario[e]
[f 0 5 -258][f 2 1]Pasar tiempo con...[e]
[f 0 5 -258][f 2 1]Guardar[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[sel ShoppingDistrict]
[f 0 5 -258][f 2 1]Calle comercial, Sur[e]
[f 0 5 -258][f 2 1]Calle comercial, Norte[e]
[f 0 5 -258][f 2 1]Shiroku[e]
[f 0 5 -258][f 2 1]Habitación Terciopelo[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[msg MSG_MARIE_VELVET_IN [Marie]]
[f 0 5 -258][f 2 1][f 4 6 60 1 0 1]¿Vas a entrar? Yo también voy.[n][f 1 1][e]

[msg MARGARET_GOJITUDAN_01 [Margaret]]
[f 0 5 -258][f 2 1][f 4 6 34 1 0 1]Ah... Hola.[n][f 1 1][e]

[msg MSG_0320_AFTER_E428002]
[f 0 5 -258][f 2 1]> Ha empezado a llover.[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED]
[f 0 5 -258][f 2 1]> No tienes ninguna razón[n]para estar aquí.[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO]
[f 0 5 -258][f 2 1]> Tienes la sensación de que no has[n]acabado de despedirte de todo el mundo.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> ¿Quieres volver a casa y[n]prepararte para mañana?[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL]
[f 0 5 -258][f 2 1]> Tienes la sensación de que no te has[n]despedido de todos tus seres queridos.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> ¿Quieres volver a casa y[n]prepararte para mañana?[n][f 1 1][e]

[msg MSG_0320_RETURN_HOME]
[f 0 5 -258][f 2 1]> ¿Quieres volver a casa y[n]prepararte para mañana?[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO2]
[f 0 5 -258][f 2 1]> No tienes ninguna razón[n]para estar aquí.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Aún no has hablado con algunos de[n]tus seres queridos.[n][f 1 1][e]


[msg MSG_0320_RETURN_HOME2]
[f 0 5 -258][f 2 1]> No tienes ninguna razón[n]para estar aquí.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Es hora de volver a casa y[n]prepararse para mañana...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL3]
[f 0 5 -258][f 2 1]> No tienes ninguna razón[n]para estar aquí.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Ahora has dicho adiós a todos[n]tus seres queridos.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> ¿Hay algo más que aún[n]tengas que hacer aquí...?[n][f 1 1][e]

[msg MSG_0417_VELVET_DONOTENT]
[f 0 5 -258][f 2 1]> No necesitas entrar aquí...[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED3]
[f 0 5 -258][f 2 1]> No hay razón para que estés aquí...[n][f 1 1][e]

[msg MSG_0320_DOUJIMA_SEARCH]
[f 0 5 -258][f 2 1]> Deberías buscar a Dojima y Nanako.[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL2]
[f 0 5 -258][f 2 1]> No deberías tener razón para venir[n]aquí...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Ahora has dicho adiós a todos[n]tus seres queridos.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Es hora de volver a casa y[n]prepararse para mañana...[n][f 1 1][e]

[msg EQUIP_SHOP_STOP]
[s]> Hay un hombre con aspecto duro[n]aporreando algo en la parte trasera[n]de la tienda.[n][w][e]
[s]> Has decidido no entrar.[n][w][e]

[msg EQUIP_SHOP_CLOSED]
[s]> La tienda ya ha cerrado hoy.[n][w][e]

[msg MSG_ITEMSHOP_0411]
[s]> Hay distintos productos[n]en las estanterías.[n][w][e]
[s]> Hay una señora con aspecto[n]simpático sentada detrás del mostrador.[n][w][e]

[msg MSG_0320_NOMORE_NEED2]
[s]> No hay razón para que estés aquí...[n][w][e]

[msg MSG_0320_GO_HOME_COMU_NO_2]
[s]> No tienes ninguna razón[n]para estar aquí.[n][w][e]
[s]> Aún no has hablado con algunos de[n]tus seres queridos.[n][w][e]

[msg MSG_0320_GO_HOME_COMU_AL_2]
[s]> No deberías tener razón para venir[n]aquí...[n][w][e]
[s]> Ahora has dicho adiós a todos[n]tus seres queridos.[n][w][e]
[s]> Es hora de volver a casa y[n]prepararse para mañana...[n][w][e]

[msg MSG_0320_RETURN_HOME2]
[s]> No tienes ninguna razón[n]para estar aquí.[n][w][e]
[s]> Es hora de volver a casa y[n]prepararse para mañana...[n][w][e]

[msg MSG_0320_NOMORE_NEED3]
[s]> No hay razón para que estés aquí...[n][w][e]

[msg MSG_0320_GO_HOME_COMU_AL_3]
[s]> No tienes ninguna razón[n]para estar aquí.[n][w][e]
[s]> Ahora has dicho adiós a todos[n]tus seres queridos.[n][w][e]
[s]> ¿Hay algo más que aún[n]tengas que hacer aquí...?[n][w][e]

[msg MSG_0417_VELVET_DONOTENT]
[s]> No necesitas entrar aquí...[n][w][e]
