[msg item_38C]
[s]When used as bait at the[n]river, can attract Red[n]Goldfish.[n][e]

[msg item_38D]
[s]When used as bait at the[n]river, can attract Genji[n]Ayu or Amber Seema.[n][e]

[msg item_38E]
[s]When used as bait at the[n]river, can attract Inaba[n]Trout.[n][e]

[msg item_38F]
[s]When used as bait at the[n]river, can attract Huge[n]Fish.[n][e]

[msg item_390]
[s]When used as bait at the[n]river, can attract the[n]Guardian.[n][e]

[msg item_391]
[s]When used as bait at the[n]sea, can attract Hachiro[n]Octopus.[n][e]

[msg item_392]
[s]When used as bait at the[n]sea, can attract Meguro[n]Tuna.[n][e]

[msg item_393]
[s]When used as bait at the[n]sea, can attract the[n]Sea Guardian.[n][e]