[msg SquareMenuConfig]
[s][clr 1]Custom Sub Menu Setup[clr 0][n]Selecciona las funciones que[n]quieres utilizar. Las opciones[n]recomendadas están habilitadas por defecto.[n][w][e]

[s][clr 1]Custom Sub Menu Setup[clr 0][n]Estos ajustes se pueden modificar en[n]cualquier momento durante tu partida.[n][w][e]

[sel ToggleMenu]
[f 0 5 -258][f 2 1]Sí[e]
[f 0 5 -258][f 2 1]No[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[sel YesNo]
[f 0 5 -258][f 2 1]Sí[e]
[f 0 5 -258][f 2 1]No[e]

[msg SquareMenuOptions_Text]
[f 0 5 -258][f 2 1]Opciones (1/2 Atrás para Salir)[f 1 1][e]

[msg SquareMenuOptions_Text_2]
[f 0 5 -258][f 2 1]Opciones (2/2 Atrás para Salir)[f 1 1][e]

[sel SquareMenuOptions]
[f 0 5 -258][f 2 1]Mod Menu: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Quick Travel Plus: [f 2 4 1][e]
[f 0 5 -258][f 2 1]Mobile Calendar: [f 2 4 2][e]
[f 0 5 -258][f 2 1]Dungeon Options: [f 2 4 3][e]
[f 0 5 -258][f 2 1]Find A Friend: [f 2 4 4][e]
[f 0 5 -258][f 2 1]Save Anywhere: [f 2 4 5][e]
[f 0 5 -258][f 2 1]Game Over Skip: [f 2 4 6][e]
[f 0 5 -258][f 2 1]Reap-Balanced Encounters: [f 2 4 7][e]
[f 0 5 -258][f 2 1]Default Direct Commands: [f 2 4 8][e]
[f 0 5 -258][f 2 1]Siguiente[e]
[f 0 5 -258][f 2 1]Anterior[e]

[msg OptionsWarning]
[f 0 5 -258][f 2 1]Accede al Menú de Opciones nuevamente[n]presionando el [f 0 1 2]botón del Menú de[n]Comandos[f 0 1 0] desde arriba del Sub menú.[f 1 1][e]

[msg ModMenu_About[Mod Menu (Sierra/ShrineFox)]]
[f 0 5 -258][f 2 1]A powerful tool for modders. Enables options for
[n]calling of fields and events, toggling of flags,
[n]stat editing and much more. Use with caution![e]

[msg QuickTravelPlus_About[Quick Travel Plus (ShrineFox)]]
[f 0 5 -258][f 2 1]Ajuste de QOL inspirado en P5. Amplía 
[n]los menús de viaje rápido (submenú y mapa)[n]con más 
ubicaciones.[e]

[msg MobileCalendar_About[Mobile Calendar (ShrineFox)]]
[f 0 5 -258][f 2 1]Permite acceder al calendario desde cualquier[n]lugar a través del submenú. Mejor conocido como[n]el mod de "Calendario útil" como un QOL.[e]

[msg DungeonOptions_About[Dungeon Options (Tekka)]]
[f 0 5 -258][f 2 1]Ajustes de QOL configurables para la[n]exploración de mazmorras.[n]Activa para ver las opciones disponibles.[e]

[msg FindAFriend_About[FindAFriend (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Ajuste de QOL para hacer el seguimiento de los V.[n]Sociales menos tedioso. Agrega una[n]opción de viaje rápido cuando esté disponible.[e]

[msg SaveAnywhere_About[Save Anywhere (Tupelov)]]
[f 0 5 -258][f 2 1]Guarda tu partida desde cualquier lugar, directamente[n]desde el submenú. Normalmente, solo podrías[n]guardar en ciertas áreas de mariposas azules.[e]

[msg GameOverskip_About[Game Over Skip (Tekka)]]
[f 0 5 -258][f 2 1]Cuando esté activado, la escena de la Habitación[n]Terciopelo será omitida si mueres. Se te[n]preguntará para volver a intentarlo.[e]

[msg ConsistentReaper_About[Reap-Balanced Encounters (Tekka)]]
[f 0 5 -258][f 2 1]Ajuste de QOL para eliminar la aleatoriedad del[n]con el Segador. El 22vo cofre siempre tendrá[n]un Segador. Cambia de piso para reiniciar.[e]

[msg DirectCommands_About[Default Direct Commands (Tekka)]]
[f 0 5 -258][f 2 1]Cuando esté activado, las tácticas del grupo[n]se establecerán en "Comandos Directos" de[n]forma predeterminada.[e]

[msg DungeonOptions_Text]
[f 0 5 -258][f 2 1]Opciones de Mazmorra[e]

[sel DungeonOptions]
[f 0 5 -258][f 2 1]Mostrar Zorro: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Mostrar Selección de Piso: [f 2 4 1][e]
[f 0 5 -258][f 2 1]Mostrar Talue-Go: [f 2 4 2][e]
[f 0 5 -258][f 2 1]Mostrar Organizar Grupo: [f 2 4 3][e]
[f 0 5 -258][f 2 1]Listo[e]

[msg ShowFox_About[Mostrar Zorro (Tekka)]]
[f 0 5 -258][f 2 1]Permite comprar curación del Zorro en[n]cualquier lugar a través del submenú.[n]Normalmente tendrías que volver a la entrada.[e]

[msg FloorSelect_About[Piso (Tekka)]]
[f 0 5 -258][f 2 1]Ajuste de QOL que se activa después de la[n]fecha límite de una mazmorra.[n]Te permite viajar rápidamente a cualquier piso.[e]

[msg GohoM_About[Talue-Go (Tekka)]]
[f 0 5 -258][f 2 1]Ajuste de QOL inspirado en P5. Agrega una opción al[n]submenú que te permite usar rápidamente tus Talue-Go,[n]sin necesidad de buscar en tus objetos.[e]

[msg OrganizeParty_About[Organizar Grupo (Tekka)]]
[f 0 5 -258][f 2 1]Ajuste de QOL que te permite intercambiar miembros[n]del grupo con una opción del submenú sin[n]necesidad de salir de una mazmorra.[e]

[msg FindAFriendOptions_Text]
[f 0 5 -258][f 2 1]Find A Friend Options[e]

[sel FindAFriendOptions]
[f 0 5 -258][f 2 1]Modo Sin Spoilers: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Listo[e]

[msg SPOILER_TOGGLE[FindAFriend (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Si está en "Sí", solo se mostrarán los[n]V. Sociales que hayas descubierto[n]y comenzado su Rango 1.[e]

[msg IntroSkipConfig]
[f 0 5 -258][f 2 1][f 0 1 1]Prologue Skip Setup[n]
[f 0 1 0]Los eventos del prologo de P4G son[n]notoriamente largos, abarcando de 1 a 3[n]horas antes de comenzar el juego real.[f 1 1][e]

[msg IntroSkipSelection[Prologue Skip (ShrineFox)]]
[f 0 5 -258][f 2 1]¿Te gustaría omitir el prologo y comenzar[n]desde el 20 de abril? No se recomienda para[n]jugadores que están jugando por primera vez.[f 1 1][e]

[msg ShowFoxOptions_Text]
[f 0 5 -258][f 2 1]Mostrar Zorro[e]

[sel ShowFoxOptions]
[f 0 5 -258][f 2 1]Usar Talue-Go: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Listo[e]

[msg ShowFox_GohoM[Zorro Talue-Go (Tekka)]]
[f 0 5 -258][f 2 1]Ajuste diseñado para mejorar el equilibrio.[n]Si está en "Sí", llamar al zorro requerirá[n]un [f 2 5 3 -1 2] o un [f 2 5 3 -1 3].[e]