[msg NightHangoutHelp]
[f 2 1][f 4 7 0]By spending time in the shopping district at[n]night with those you have formed Social Links[n]with, you can become even closer to them.[n][f 1 1][e]
[f 2 1]But keep in mind that the Social Link [f 0 1 2]cannot[n]progress to the next rank[f 0 1 0] at night, since[n]your time is limited.[n][f 1 1][e]
[f 2 1]You only have so many days to develop the[n]bonds you form in Inaba.[n][f 1 1][e]
[f 2 1]At night, you can become closer to those whose[n]Social Links you wish to develop, and then[n]take them to the next rank during the day![n][f 1 1][e]
[f 2 1]You can also chat with those you have[n]formed Social Links with. When chatting with[n]someone you [f 0 1 2]won't be able to become[n]closer with them and time will not advance[f 0 1 0].[n][f 1 1][e]
[f 2 1]You will experience the same events when chatting[n]and spending time with someone, so you can[n]chat when you have something else to do [n]at night but still want to talk![n][f 1 1][e]

[msg ChatHelp]
[f 2 1]You can now chat with those you have[n]formed Social Links with. When chatting with[n]someone you [f 0 1 2]won't be able to become[n]closer with them and time will not advance[f 0 1 0].[n][f 1 1][e]
[f 2 1]You will experience the same events when chatting[n]and spending time with someone, so you can[n]chat when you have something else to do [n]at night but still want to talk![n][f 1 1][e]

[sel HangoutSel top]
[f 2 1]Spend time with [f 2 4 7][e]
[f 2 1]Chat with [f 2 4 7][e]
[f 2 1]Cancel[e]

[sel DaisukeHangoutSel top]
[f 2 1]Spend time with Daisuke[e]
[f 2 1]Chat with Daisuke[e]
[f 2 1]Cancel[e]

[sel KouHangoutSel top]
[f 2 1]Spend time with Kou[e]
[f 2 1]Chat with Kou[e]
[f 2 1]Cancel[e]

[msg NightWaitSuggestion]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> You feel your relationship with [f 2 4 7][n]could become stronger soon if you[n]had more time...[n][f 1 1][e]

[msg NightWaitSuggestionKou]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> You feel your relationship with Kou[n]could become stronger soon if you[n]had more time...[n][f 1 1][e]

[msg NightWaitSuggestionDaisuke]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> You feel your relationship with Daisuke[n]could become stronger soon if you[n]had more time...[n][f 1 1][e]

