[msg DEATH_BOX]
[f 0 5 65278][f 2 1]> You sense an intensely terrifying[n]presence...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> Open this chest?[n][f 1 1][e]

[msg DEATH_ENCOUNT]
[f 0 5 65278][f 2 1]> Something jumped out of the chest![n][f 1 1][e]

[msg LOCK_BOX]
[f 0 5 65278][f 2 1]> The treasure chest is locked...[n][f 1 1][e]

[msg USE_MUGI_OK]
[f 0 5 65278][f 2 1]> Open the treasure chest with Crack Wheat?[n]    (Crack Wheat remaining: [f 0 1 1][f 2 4 0][f 0 1 0])[n][f 1 1][e]

[msg USE_KEY_OK]
[f 0 5 65278][f 2 1]> Open the treasure chest with a key?[n]    (Chest Keys remaining: [f 0 1 1][f 2 4 0][f 0 1 0])[n][f 1 1][e]

[msg TRAPBOX_ENCOUNT]
[f 0 5 65278][f 2 1]> A Shadow jumped out of the chest![n][f 1 1][e]

[msg HELP_STAIR_KUMA [Teddie]]
[f 0 5 65278][f 2 1]We found the stairs![n][f 1 1][e]
[f 0 5 65278][f 2 1]I can lead you there anytime![n][f 1 1][e]

[msg FIND_BOX_YOSUKE_01]
[f 0 5 65278][f 2 1]Ooh. We found a chest![n][f 1 6 50][e]

[msg FIND_BOX_YOSUKE_02]
[f 0 5 65278][f 2 1]Huh? A treasure chest![n]Let's open it![n][f 1 6 50][e]

[msg FIND_BOX_YOSUKE_03]
[f 0 5 65278][f 2 1]Huh? Isn't that[n]a chest there?[n][f 1 6 50][e]

[msg FIND_STAIR_YOSUKE_01]
[f 0 5 65278][f 2 1]Ooh! Stairs here![n][f 1 6 50][e]

[msg FIND_STAIR_YOSUKE_02]
[f 0 5 65278][f 2 1]We found the stairs![n]Let's move on![n][f 1 6 50][e]

[msg FIND_STAIR_YOSUKE_03]
[f 0 5 65278][f 2 1]All right, the stairs![n]Let's go![n][f 1 6 50][e]

[msg FIND_ENEMY_YOSUKE_01]
[f 0 5 65278][f 2 1]Whoa, a Shadow![n][f 1 6 50][e]

[msg FIND_ENEMY_YOSUKE_02]
[f 0 5 65278][f 2 1]We found a Shadow![n][f 1 6 50][e]

[msg FIND_ENEMY_YOSUKE_03]
[f 0 5 65278][f 2 1]Ugh... Another one...[n][f 1 6 50][e]

[msg FIND_PLAYER_YOSUKE_01]
[f 0 5 65278][f 2 1]Hey, my man![n][f 1 6 50][e]

[msg FIND_PLAYER_YOSUKE_02]
[f 0 5 65278][f 2 1]Hey![n]How's it going there?[n][f 1 6 50][e]

[msg FIND_CHIE_YOSUKE_01]
[f 0 5 65278][f 2 1]Oh, it's Chie![n]You doin' okay?[n][f 1 6 50][e]

[msg FIND_CHIE_YOSUKE_02]
[f 0 5 65278][f 2 1]Yo, Chie![n][f 1 6 50][e]

[msg FIND_YUKIKO_YOSUKE_01]
[f 0 5 65278][f 2 1]Ah, it's Yukiko...[n]What're you doing?[n][f 1 6 50][e]

[msg FIND_YUKIKO_YOSUKE_02]
[f 0 5 65278][f 2 1]'Sup, Yukiko![n][f 1 6 50][e]

[msg FIND_KANJI_YOSUKE_01]
[f 0 5 65278][f 2 1]Ooh, we found a punk![n][f 1 6 50][e]

[msg FIND_KANJI_YOSUKE_02]
[f 0 5 65278][f 2 1]Yo, Kanji![n][f 1 6 50][e]

[msg FIND_NAOTO_YOSUKE_01]
[f 0 5 65278][f 2 1]Hey, Naoto![n]What're ya doing there?[n][f 1 6 50][e]

[msg FIND_NAOTO_YOSUKE_02]
[f 0 5 65278][f 2 1]Yo, kid![n][f 1 6 50][e]

[msg FIND_KUMA_YOSUKE_01]
[f 0 5 65278][f 2 1]Hey, Teddie![n]Same as always?[n][f 1 6 50][e]

[msg FIND_KUMA_YOSUKE_02]
[f 0 5 65278][f 2 1]Oh, Ted![n][f 1 6 50][e]

[msg FIND_FIX_YOSUKE_01]
[f 0 5 65278][f 2 1]Hey, it's the fox![n]What're you doing here?[n][f 1 6 50][e]

[msg FIND_FIX_YOSUKE_02]
[f 0 5 65278][f 2 1]Oh, the fox![n][f 1 6 50][e]

[msg FIND_BOX_CHIE_01]
[f 0 5 65278][f 2 1]Oh, a treasure chest![n][f 1 6 50][e]

[msg FIND_BOX_CHIE_02]
[f 0 5 65278][f 2 1]Treasure spotted![n][f 1 6 50][e]

[msg FIND_BOX_CHIE_03]
[f 0 5 65278][f 2 1]Ooh, a treasure chest![n]Try opening it![n][f 1 6 50][e]

[msg FIND_STAIR_CHIE_01]
[f 0 5 65278][f 2 1]We found the stairs![n][f 1 6 50][e]

[msg FIND_STAIR_CHIE_02]
[f 0 5 65278][f 2 1]We found the stairs! Let's[n]hurry to the next floor.[n][f 1 6 50][e]

[msg FIND_STAIR_CHIE_03]
[f 0 5 65278][f 2 1]Ooh, stairs right here![n]Why don't we go on ahead?[n][f 1 6 50][e]

[msg FIND_ENEMY_CHIE_01]
[f 0 5 65278][f 2 1]Sheesh, a Shadow![n][f 1 6 50][e]

[msg FIND_ENEMY_CHIE_02]
[f 0 5 65278][f 2 1]Argh! There's a Shadow![n][f 1 6 50][e]

[msg FIND_ENEMY_CHIE_03]
[f 0 5 65278][f 2 1]There's a Shadow here,[n]too...[n][f 1 6 50][e]

[msg FIND_PLAYER_CHIE_01]
[f 0 5 65278][f 2 1]Hey there![n][f 1 6 50][e]

[msg FIND_PLAYER_CHIE_02]
[f 0 5 65278][f 2 1]Oh, doing okay?[n][f 1 6 50][e]

[msg FIND_YOSUKE_CHIE_01]
[f 0 5 65278][f 2 1]Oh, Yosuke![n]Are you just chilling here?[n][f 1 6 50][e]

[msg FIND_YOSUKE_CHIE_02]
[f 0 5 65278][f 2 1]Hey, it's Yosuke![n][f 1 6 50][e]

[msg FIND_YUKIKO_CHIE_01]
[f 0 5 65278][f 2 1]Oh, Yukiko![n]What're you doing?[n][f 1 6 50][e]

[msg FIND_YUKIKO_CHIE_02]
[f 0 5 65278][f 2 1]Ooh, Yukiko![n][f 1 6 50][e]

[msg FIND_KANJI_CHIE_01]
[f 0 5 65278][f 2 1]Hey, Kanji-kun![n]What are you doing here?[n][f 1 6 50][e]

[msg FIND_KANJI_CHIE_02]
[f 0 5 65278][f 2 1]What's up, Kanji-kun?[n][f 1 6 50][e]

[msg FIND_NAOTO_CHIE_01]
[f 0 5 65278][f 2 1]Naoto-kun's here![n]Is something wrong?[n][f 1 6 50][e]

[msg FIND_NAOTO_CHIE_02]
[f 0 5 65278][f 2 1]Oh, it's Naoto-kun![n][f 1 6 50][e]

[msg FIND_KUMA_CHIE_01]
[f 0 5 65278][f 2 1]Teddie![n]Keep up the good work![n][f 1 6 50][e]

[msg FIND_KUMA_CHIE_02]
[f 0 5 65278][f 2 1]Teddie![n][f 1 6 50][e]

[msg FIND_FOX_CHIE_01]
[f 0 5 65278][f 2 1]Hey, Foxy![n]Whatcha doin'?[n][f 1 6 50][e]

[msg FIND_FOX_CHIE_02]
[f 0 5 65278][f 2 1]Look, it's the fox![n][f 1 6 50][e]

[msg FIND_BOX_YUKIKO_01]
[f 0 5 65278][f 2 1]Oh, we found a[n]treasure chest![n][f 1 6 50][e]

[msg FIND_BOX_YUKIKO_02]
[f 0 5 65278][f 2 1]Is this treasure?[n][f 1 6 50][e]

[msg FIND_BOX_YUKIKO_03]
[f 0 5 65278][f 2 1]A treasure chest![n]Do you want to open it?[n][f 1 6 50][e]

[msg FIND_STAIR_YUKIKO_01]
[f 0 5 65278][f 2 1]Ah, so here's the stairway.[n][f 1 6 50][e]

[msg FIND_STAIR_YUKIKO_02]
[f 0 5 65278][f 2 1]There's the stairway![n]Let's hurry ahead![n][f 1 6 50][e]

[msg FIND_STAIR_YUKIKO_03]
[f 0 5 65278][f 2 1]We found the stairway.[n]Shall we go on?[n][f 1 6 50][e]

[msg FIND_ENEMY_YUKIKO_01]
[f 0 5 65278][f 2 1]An enemy! Be careful![n][f 1 6 50][e]

[msg FIND_ENEMY_YUKIKO_02]
[f 0 5 65278][f 2 1]We found a Shadow![n]Are you ready?[n][f 1 6 50][e]

[msg FIND_ENEMY_YUKIKO_03]
[f 0 5 65278][f 2 1]Shadows here, too...?[n][f 1 6 50][e]

[msg FIND_PLAYER_YUKIKO_01]
[f 0 5 65278][f 2 1]Oh, there you are![n][f 1 6 50][e]

[msg FIND_PLAYER_YUKIKO_02]
[f 0 5 65278][f 2 1]Good work![n]Are you feeling all right?[n][f 1 6 50][e]

[msg FIND_YOSUKE_YUKIKO_01]
[f 0 5 65278][f 2 1]Yosuke-kun![n]Did you come all this way?[n][f 1 6 50][e]

[msg FIND_YOSUKE_YUKIKO_02]
[f 0 5 65278][f 2 1]Oh, Yosuke-kun![n][f 1 6 50][e]

[msg FIND_CHIE_YUKIKO_01]
[f 0 5 65278][f 2 1]Chie! I'm so happy[n]to see you here![n][f 1 6 50][e]

[msg FIND_CHIE_YUKIKO_02]
[f 0 5 65278][f 2 1]Oh, Chie![n][f 1 6 50][e]

[msg FIND_KANJI_YUKIKO_01]
[f 0 5 65278][f 2 1]Oh, Kanji-kun![n]You've been working hard![n][f 1 6 50][e]

[msg FIND_KANJI_YUKIKO_02]
[f 0 5 65278][f 2 1]Hello, Kanji-kun![n][f 1 6 50][e]

[msg FIND_NAOTO_YUKIKO_01]
[f 0 5 65278][f 2 1]Naoto-kun![n]What's wrong?[n][f 1 6 50][e]

[msg FIND_NAOTO_YUKIKO_02]
[f 0 5 65278][f 2 1]Oh, Naoto-kun![n][f 1 6 50][e]

[msg FIND_KUMA_YUKIKO_01]
[f 0 5 65278][f 2 1]Teddie, are you all right?[n][f 1 6 50][e]

[msg FIND_KUMA_YUKIKO_02]
[f 0 5 65278][f 2 1]Oh, it's Teddie![n][f 1 6 50][e]

[msg FIND_FOX_YUKIKO_01]
[f 0 5 65278][f 2 1]What are you doing[n]here, fox-san?[n][f 1 6 50][e]

[msg FIND_FOX_YUKIKO_02]
[f 0 5 65278][f 2 1]Oh, it's the fox![n][f 1 6 50][e]

[msg FIND_BOX_KANJI_01]
[f 0 5 65278][f 2 1]Treasure![n][f 1 6 50][e]

[msg FIND_BOX_KANJI_02]
[f 0 5 65278][f 2 1]We found a treasure chest![n][f 1 6 50][e]

[msg FIND_BOX_KANJI_03]
[f 0 5 65278][f 2 1]Hey, we found a chest.[n]Let's pop this sucker open![n][f 1 6 50][e]

[msg FIND_STAIR_KANJI_01]
[f 0 5 65278][f 2 1]Stairs here![n][f 1 6 50][e]

[msg FIND_STAIR_KANJI_02]
[f 0 5 65278][f 2 1]Ooh, the stairs![n]Let's go![n][f 1 6 50][e]

[msg FIND_STAIR_KANJI_03]
[f 0 5 65278][f 2 1]It's the stairs.[n]Ready to move on?[n][f 1 6 50][e]

[msg FIND_ENEMY_KANJI_01]
[f 0 5 65278][f 2 1]We found a Shadow![n]Let's crush it![n][f 1 6 50][e]

[msg FIND_ENEMY_KANJI_02]
[f 0 5 65278][f 2 1]All right, an enemy![n][f 1 6 50][e]

[msg FIND_ENEMY_KANJI_03]
[f 0 5 65278][f 2 1]There's one...[n][f 1 6 50][e]

[msg FIND_PLAYER_KANJI_01]
[f 0 5 65278][f 2 1]Oh, hey.[n][f 1 6 50][e]

[msg FIND_PLAYER_KANJI_02]
[f 0 5 65278][f 2 1]Are you doing okay?[n][f 1 6 50][e]

[msg FIND_YOSUKE_KANJI_01]
[f 0 5 65278][f 2 1]Hey, Yosuke-senpai![n][f 1 6 50][e]

[msg FIND_YOSUKE_KANJI_02]
[f 0 5 65278][f 2 1]Oh, it's Yosuke-senpai![n][f 1 6 50][e]

[msg FIND_CHIE_KANJI_01]
[f 0 5 65278][f 2 1]Chie-senpai, what's up![n][f 1 6 50][e]

[msg FIND_CHIE_KANJI_02]
[f 0 5 65278][f 2 1]Yo, Chie-senpai![n][f 1 6 50][e]

[msg FIND_YUKIKO_KANJI_01]
[f 0 5 65278][f 2 1]Yukiko-senpai, keep[n]up the good work![n][f 1 6 50][e]

[msg FIND_YUKIKO_KANJI_02]
[f 0 5 65278][f 2 1]Hey Yukiko-senpai![n][f 1 6 50][e]

[msg FIND_NAOTO_KANJI_01]
[f 0 5 65278][f 2 1]O-Oh, it's Naoto...[n]What're ya doin'?[n][f 1 6 50][e]

[msg FIND_NAOTO_KANJI_02]
[f 0 5 65278][f 2 1]Oh, h-hi there, Naoto![n][f 1 6 50][e]

[msg FIND_KUMA_KANJI_01]
[f 0 5 65278][f 2 1]Yo, Teddie![n][f 1 6 50][e]

[msg FIND_KUMA_KANJI_02]
[f 0 5 65278][f 2 1]Oh, it's just you, Ted...[n][f 1 6 50][e]

[msg FIND_FOX_KANJI_01]
[f 0 5 65278][f 2 1]Ooh! It's the fox![n][f 1 6 50][e]

[msg FIND_FOX_KANJI_02]
[f 0 5 65278][f 2 1]Well, hello there, fox.[n][f 1 6 50][e]

[msg FIND_BOX_KUMA_01]
[f 0 5 65278][f 2 1]Wooo, we found a chest![n][f 1 6 50][e]

[msg FIND_BOX_KUMA_02]
[f 0 5 65278][f 2 1]Treasure ahoy![n][f 1 6 50][e]

[msg FIND_BOX_KUMA_03]
[f 0 5 65278][f 2 1]A treasure chest![n]Let's open it![n][f 1 6 50][e]

[msg FIND_STAIR_KUMA_01]
[f 0 5 65278][f 2 1]Stairs! Should we[n]go on ahead?[n][f 1 6 50][e]

[msg FIND_STAIR_KUMA_02]
[f 0 5 65278][f 2 1]Stairs right here![n][f 1 6 50][e]

[msg FIND_STAIR_KUMA_03]
[f 0 5 65278][f 2 1]We found the stairs![n][f 1 6 50][e]

[msg FIND_ENEMY_KUMA_01]
[f 0 5 65278][f 2 1]We found the enemy![n]Be careful![n][f 1 6 50][e]

[msg FIND_ENEMY_KUMA_02]
[f 0 5 65278][f 2 1]Shadows![n]Let's get 'em![n][f 1 6 50][e]

[msg FIND_ENEMY_KUMA_03]
[f 0 5 65278][f 2 1]We found a Shadow![n]I'll take'em on![n][f 1 6 50][e]

[msg FIND_PLAYER_KUMA_01]
[f 0 5 65278][f 2 1]Huh? We found you![n][f 1 6 50][e]

[msg FIND_PLAYER_KUMA_02]
[f 0 5 65278][f 2 1]How are you doing?[n][f 1 6 50][e]

[msg FIND_YOSUKE_KUMA_01]
[f 0 5 65278][f 2 1]Yosuke, you okay?[n][f 1 6 50][e]

[msg FIND_YOSUKE_KUMA_02]
[f 0 5 65278][f 2 1]Ooh, Yosuke![n][f 1 6 50][e]

[msg FIND_CHIE_KUMA_01]
[f 0 5 65278][f 2 1]Chie-chan![n]How long's it been![n][f 1 6 50][e]

[msg FIND_CHIE_KUMA_02]
[f 0 5 65278][f 2 1]Ooh, it's Chie-chan![n][f 1 6 50][e]

[msg FIND_YUKIKO_KUMA_01]
[f 0 5 65278][f 2 1]Yuki-chan! Konnichiwa![n][f 1 6 50][e]

[msg FIND_YUKIKO_KUMA_02]
[f 0 5 65278][f 2 1]Ooh, Yuki-chan![n][f 1 6 50][e]

[msg FIND_KANJI_KUMA_01]
[f 0 5 65278][f 2 1]Kanji! Nice work![n][f 1 6 50][e]

[msg FIND_KANJI_KUMA_02]
[f 0 5 65278][f 2 1]Hey, it's Kanji![n][f 1 6 50][e]

[msg FIND_NAOTO_KUMA_01]
[f 0 5 65278][f 2 1]Nao-chan! Doing good?[n][f 1 6 50][e]

[msg FIND_NAOTO_KUMA_02]
[f 0 5 65278][f 2 1]Ooh, Nao-chan![n][f 1 6 50][e]

[msg FIND_FOX_KUMA_01]
[f 0 5 65278][f 2 1]Heya, Kitsu-chan![n][f 1 6 50][e]

[msg FIND_FOX_KUMA_02]
[f 0 5 65278][f 2 1]Hey, Foxy![n][f 1 6 50][e]

[msg FIND_BOX_RISE_01]
[f 0 5 65278][f 2 1]We found a chest![n][f 1 6 50][e]

[msg FIND_BOX_RISE_02]
[f 0 5 65278][f 2 1]It's a treasure chest![n]Why don't you open it?[n][f 1 6 50][e]

[msg FIND_BOX_RISE_03]
[f 0 5 65278][f 2 1]Oh, treasure![n][f 1 6 50][e]

[msg FIND_STAIR_RISE_01]
[f 0 5 65278][f 2 1]It's the stairway![n]Wanna go on ahead?[n][f 1 6 50][e]

[msg FIND_STAIR_RISE_02]
[f 0 5 65278][f 2 1]Hey, it's the stairs![n][f 1 6 50][e]

[msg FIND_STAIR_RISE_03]
[f 0 5 65278][f 2 1]Stairs located![n]Let's go![n][f 1 6 50][e]

[msg FIND_ENEMY_RISE_01]
[f 0 5 65278][f 2 1]There's enemies over[n]there! Be careful![n][f 1 6 50][e]

[msg FIND_ENEMY_RISE_02]
[f 0 5 65278][f 2 1]Enemy Shadows![n]Take care![n][f 1 6 50][e]

[msg FIND_ENEMY_RISE_03]
[f 0 5 65278][f 2 1]There are enemies over[n]there. Be careful![n][f 1 6 50][e]

[msg FIND_YOSUKE_RISE_01]
[f 0 5 65278][f 2 1]It's Yosuke-senpai![n]What are you doing?[n][f 1 6 50][e]

[msg FIND_YOSUKE_RISE_02]
[f 0 5 65278][f 2 1]Oh, Yosuke-senpai![n][f 1 6 50][e]

[msg FIND_CHIE_RISE_01]
[f 0 5 65278][f 2 1]Chie-senpai, hello![n][f 1 6 50][e]

[msg FIND_CHIE_RISE_02]
[f 0 5 65278][f 2 1]Hi there, Chie-senpai![n][f 1 6 50][e]

[msg FIND_YUKIKO_RISE_01]
[f 0 5 65278][f 2 1]Yukiko-senpai![n]Are you all right?[n][f 1 6 50][e]

[msg FIND_YUKIKO_RISE_02]
[f 0 5 65278][f 2 1]Hi there, Yukiko-senpai![n][f 1 6 50][e]

[msg FIND_KANJI_RISE_01]
[f 0 5 65278][f 2 1]Kanji, how are you?[n][f 1 6 50][e]

[msg FIND_KANJI_RISE_02]
[f 0 5 65278][f 2 1]Oh, it's Kanji![n][f 1 6 50][e]

[msg FIND_NAOTO_RISE_01]
[f 0 5 65278][f 2 1]Naoto, how are you doing?[n][f 1 6 50][e]

[msg FIND_NAOTO_RISE_02]
[f 0 5 65278][f 2 1]Ooh, it's Naoto![n][f 1 6 50][e]

[msg FIND_KUMA_RISE_01]
[f 0 5 65278][f 2 1]Teddie, still have[n]energy in you?[n][f 1 6 50][e]

[msg FIND_KUMA_RISE_02]
[f 0 5 65278][f 2 1]Ooh, we found Teddie![n][f 1 6 50][e]

[msg FIND_FOX_RISE_01]
[f 0 5 65278][f 2 1]Oh, Fox-kun![n]What's up?[n][f 1 6 50][e]

[msg FIND_FOX_RISE_02]
[f 0 5 65278][f 2 1]Look, it's Fox-kun![n][f 1 6 50][e]

[msg FIND_BOX_NAOTO_01]
[f 0 5 65278][f 2 1]Oh, a treasure chest![n][f 1 6 50][e]

[msg FIND_BOX_NAOTO_02]
[f 0 5 65278][f 2 1]We found a treasure chest![n][f 1 6 50][e]

[msg FIND_BOX_NAOTO_03]
[f 0 5 65278][f 2 1]It looks like a treasure chest.[n]Are you going to open it?[n][f 1 6 50][e]

[msg FIND_STAIR_NAOTO_01]
[f 0 5 65278][f 2 1]Stairs have been located![n]Let's proceed ahead![n][f 1 6 50][e]

[msg FIND_STAIR_NAOTO_02]
[f 0 5 65278][f 2 1]Oh, it's the stairway![n][f 1 6 50][e]

[msg FIND_STAIR_NAOTO_03]
[f 0 5 65278][f 2 1]We found the stairs![n][f 1 6 50][e]

[msg FIND_ENEMY_NAOTO_01]
[f 0 5 65278][f 2 1]Hostile Shadows![n]Be careful![n][f 1 6 50][e]

[msg FIND_ENEMY_NAOTO_02]
[f 0 5 65278][f 2 1]Enemy Shadows... Shall we[n]wait to see what they'll do?[n][f 1 6 50][e]

[msg FIND_ENEMY_NAOTO_03]
[f 0 5 65278][f 2 1]Shadows are here,[n]as well...[n][f 1 6 50][e]

[msg FIND_PLAYER_NAOTO_01]
[f 0 5 65278][f 2 1]Oh, hello![n]Let's keep up the work![n][f 1 6 50][e]

[msg FIND_PLAYER_NAOTO_02]
[f 0 5 65278][f 2 1]How are you doing[n]on your end?[n][f 1 6 50][e]

[msg FIND_YOSUKE_NAOTO_01]
[f 0 5 65278][f 2 1]Yosuke-senpai, hello.[n][f 1 6 50][e]

[msg FIND_YOSUKE_NAOTO_02]
[f 0 5 65278][f 2 1]Oh, Yosuke-senpai![n][f 1 6 50][e]

[msg FIND_CHIE_NAOTO_01]
[f 0 5 65278][f 2 1]Chie-senpai, how is it going?[n][f 1 6 50][e]

[msg FIND_CHIE_NAOTO_02]
[f 0 5 65278][f 2 1]Oh, Chie-senpai![n][f 1 6 50][e]

[msg FIND_YUKIKO_NAOTO_01]
[f 0 5 65278][f 2 1]Yukiko-senpai, hello![n][f 1 6 50][e]

[msg FIND_YUKIKO_NAOTO_02]
[f 0 5 65278][f 2 1]Oh, Yukiko-senpai![n][f 1 6 50][e]

[msg FIND_KANJI_NAOTO_01]
[f 0 5 65278][f 2 1]Kanji-kun![n]How are you doing?[n][f 1 6 50][e]

[msg FIND_KANJI_NAOTO_02]
[f 0 5 65278][f 2 1]Oh, Kanji-kun![n][f 1 6 50][e]

[msg FIND_KUMA_NAOTO_01]
[f 0 5 65278][f 2 1]Teddie![n]You're here already?[n][f 1 6 50][e]

[msg FIND_KUMA_NAOTO_02]
[f 0 5 65278][f 2 1]Oh, Teddie![n][f 1 6 50][e]

[msg FIND_FOX_NAOTO_01]
[f 0 5 65278][f 2 1]Oh, Fox-san![n]What's wrong?[n][f 1 6 50][e]

[msg FIND_FOX_NAOTO_02]
[f 0 5 65278][f 2 1]Look, it's Fox-san![n][f 1 6 50][e]