[msg NightPassChat]
[f 2 1][f 4 7 0]> You made small talk with Yumi...[n][f 1 1][e]
[f 2 1]> You feel your relationship with Yumi[n]has grown deeper...[n][f 1 1][e]

[msg NightPassExChat]
[f 2 1][f 4 7 0]> It seems you were able to be of help[n]to Yumi...[n][f 1 1][e]

[msg ChatEnd]
[f 2 1][f 3 1 1 0 0 1778][f 4 7 0]> You saw Yumi off.[n][f 1 1][e]

[msg ChatEnd1]
[f 2 1][f 3 1 1 0 0 998][f 4 7 0]> You saw Yumi off.[n][f 1 1][e]

[msg ChatEnd2]
[f 2 1][f 3 1 1 0 0 1778][f 4 7 0]> You saw Yumi off.[n][f 1 1][e]

[msg ChatEndEx]
[f 2 1][f 4 7 0]> You saw Yumi off.[n][f 1 1][e]

