[msg NO_MORE_BOOKS]
[f 0 5 -258][f 2 1]> None of the books grab your interest.[n][f 1 1][e]

[msg NO_MORE_BOOKS_BULLETIN]
[f 0 5 -258][f 2 1]> There's nothing of interest written[n]on it.[n][f 1 1][e]

[msg BOOKSTORE_BULLETIN]
[f 0 5 -258][f 2 1]> There's a separate section for
[n]local businesses with a notice from
[n]Okina Station Bookstore:[n][f 1 1][e]

[msg BOOKSTORE_NEW_RELEASES_1 [Employee]]
[f 0 5 -258][f 2 1]Come again!
[n]New books will be available on 6/11.[n][f 1 1][e]

[msg BOOKSTORE_NEW_RELEASES_2 [Employee]]
[f 0 5 -258][f 2 1]Come again!
[n]New books will be available on 8/4.[n][f 1 1][e]

[msg BOOKSTORE_NEW_RELEASES_3 [Employee]]
[f 0 5 -258][f 2 1]Come again!
[n]New books will be available on 8/24.[n][f 1 1][e]

[msg BULLETIN_END]
[f 0 5 -258][f 2 1]> ...That's what it says.[n][f 1 1][e]

[msg BOOKSTORE_ARRIVAL]
[f 0 5 -258][f 2 1]> "[f 2 4 0]"  [f 2 4 1] yen.[n] [f 2 4 2] [n][f 1 1][e]