[msg YukikoTravelAvailable]
[s]You can now fast travel in Yukiko's Castle![n][w][e]

[msg KanjiTravelAvailable]
[s]You can now fast travel in the Steamy Bathhouse![n][w][e]

[msg RiseTravelAvailable]
[s]You can now fast travel in Marakyu Striptease![n][w][e]

[msg MitsuoTravelAvailable]
[s]You can now fast travel in Void Quest![n][w][e]

[msg NaotoTravelAvailable]
[s]You can now fast travel in the Secret Laboratory![n][w][e]

[msg NanakoTravelAvailable]
[s]You can now fast travel in Heaven![n][w][e]

[msg AdachiTravelAvailable]
[s]You can now fast travel in Magatsu Inaba![n][w][e]