[sel OptionSel]
[f 0 5 -258][f 2 1]Add member[e]
[f 0 5 -258][f 2 1]Remove member[e]
[f 0 5 -258][f 2 1]Finish[e]

[msg ConfirmPartyRise [Rise]]
[f 0 5 -258][f 2 1]Confirm party member changes and[n]
return to the floor entrance?[e]

[msg SelectMemberMsg]
[f 0 5 -258][f 2 1]Add which member?[e]

[msg SelectMemberMsgRise [Rise]]
[f 0 5 -258][f 2 1]Add which member?[e]

[msg ReplaceMemberMsg]
[f 0 5 -258][f 2 1]Replace which member?[e]

[msg ReplaceMemberMsgRise [Rise]]
[f 0 5 -258][f 2 1]Replace which member?[e]

[msg RemoveMemberMsg]
[f 0 5 -258][f 2 1]Remove which member?[e]

[msg RemoveMemberMsgRise [Rise]]
[f 0 5 -258][f 2 1]Remove which member?[e]

[msg OptionMsg]
[f 0 5 -258][f 2 1]What will you do?[e]

[msg OptionMsgRise [Rise]]
[f 0 5 -258][f 2 1]What will you do?[e]

[sel TOMB_SEL_HOOK]
[f 0 5 -258][f 2 1]Return to the entrance[e]
[f 0 5 -258][f 2 1]Organize party[e]
[f 0 5 -258][f 2 1]Daidara[e]
[f 0 5 -258][f 2 1]Shiroku Store[e]
[f 0 5 -258][f 2 1]Velvet Room[e]
[f 0 5 -258][f 2 1]Go back home[e]
[f 0 5 -258][f 2 1]Save[e]
[f 0 5 -258][f 2 1]Cancel[e]

[sel LIQUEUR_SEL_HOOK]
[f 0 5 -258][f 2 1]Return to the entrance[e]
[f 0 5 -258][f 2 1]Organize party[e]
[f 0 5 -258][f 2 1]Save[e]
[f 0 5 -258][f 2 1]Cancel[e]