[sel StreetNight]
[f 0 5 -258][f 2 1]Calle comercial[e]
[f 0 5 -258][f 2 1]Santuario[e]
[f 0 5 -258][f 2 1]Ribera[e]
[f 0 5 -258][f 2 1]Volver a casa[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[sel ShoppingDistrict]
[f 0 5 -258][f 2 1]Calle comercial, Sur[e]
[f 0 5 -258][f 2 1]Calle comercial, Norte[e]
[f 0 5 -258][f 2 1]Shiroku[e]
[f 0 5 -258][f 2 1]Habitación Terciopelo[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[msg MSG_MARIE_VELVET_IN [Marie]]
[f 0 5 -258][f 2 1][f 4 6 60 1 0 1]¿Vas a entrar? Yo también voy.[n][f 1 1][e]

[msg MARGARET_GOJITUDAN_01 [Margaret]]
[f 0 5 -258][f 2 1][f 4 6 34 1 0 1]Ah... Hola.[n][f 1 1][e]

[msg MSG_0320_AFTER_E428002]
[f 0 5 -258][f 2 1]> Ha empezado a llover.[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED]
[f 0 5 -258][f 2 1]> No tienes ninguna razón[n]para estar aquí.[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO]
[f 0 5 -258][f 2 1]> Tienes la sensación de que no has[n]acabado de despedirte de todo el mundo.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> ¿Quieres volver a casa y[n]prepararte para mañana?[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL]
[f 0 5 -258][f 2 1]> Tienes la sensación de que no te has[n]despedido de todos tus seres queridos.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> ¿Quieres volver a casa y[n]prepararte para mañana?[n][f 1 1][e]

[msg MSG_0320_RETURN_HOME]
[f 0 5 -258][f 2 1]> ¿Quieres volver a casa y[n]prepararte para mañana?[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO2]
[f 0 5 -258][f 2 1]> No tienes ninguna razón[n]para estar aquí.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Aún no has hablado con algunos de[n]tus seres queridos.[n][f 1 1][e]


[msg MSG_0320_RETURN_HOME2]
[f 0 5 -258][f 2 1]> No tienes ninguna razón[n]para estar aquí.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Es hora de volver a casa y[n]prepararse para mañana...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL3]
[f 0 5 -258][f 2 1]> No tienes ninguna razón[n]para estar aquí.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Ahora has dicho adiós a todos[n]tus seres queridos.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> ¿Hay algo más que aún[n]tengas que hacer aquí...?[n][f 1 1][e]

[msg MSG_0417_VELVET_DONOTENT]
[f 0 5 -258][f 2 1]> No necesitas entrar aquí...[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED3]
[f 0 5 -258][f 2 1]> No hay razón para que estés aquí...[n][f 1 1][e]

[msg MSG_0320_DOUJIMA_SEARCH]
[f 0 5 -258][f 2 1]> Deberías buscar a Dojima y Nanako.[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL2]
[f 0 5 -258][f 2 1]> No deberías tener razón para venir[n]aquí...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Ahora has dicho adiós a todos[n]tus seres queridos.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Es hora de volver a casa y[n]prepararse para mañana...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_YUKI]
[f 0 5 -258][f 2 1]> Ahora que caes, todavía[n]no te has despedido de Yukiko.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Deberías ir a la Posada Amagi.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Para ir a la [f 0 1 2]Posada Amagi,[n]dirígete a la parada de autobús[n]de la calle comercial[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_ENGE]
[f 0 5 -258][f 2 1]> Ahora que caes, todavía[n]no te has despedido de Yumi.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Deberías ir al club de teatro.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> [f 0 1 2]El club de teatro está en[n]la sala de reuniones de la primera[n]planta del edificio de prácticas[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_SUIS]
[f 0 5 -258][f 2 1]> Ahora que caes, todavía[n]no te has despedido de Ayane.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Deberías ir al aula de la banda.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> [f 0 1 2]La banda se reúne en[n]el aula de música de la primera planta[n]del edificio de prácticas[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_BASK]
[f 0 5 -258][f 2 1]> Ahora que caes, todavía[n]no te has despedido de Kou ni de Daisuke.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Recuerdas la vez[n]que fuiste al Aiya con ellos.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Deberías ir al [f 0 1 2]Aiya,[n]en la calle comercial[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_SOCC]
[f 0 5 -258][f 2 1]> Ahora que caes, todavía[n]no te has despedido de Daisuke ni de Kou.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Recuerdas la vez[n]que fuiste al Aiya con ellos.[n][f 1 1][e]
[f 0 5 -258][f 2 1] Deberías ir al [f 0 1 2]Aiya,[n]en la calle comercial[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_KITU]
[f 0 5 -258][f 2 1]> Ahora que caigo, ¿qué habrá sido[n]del zorro?[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Deberías invocar al zorro[n][f 0 1 2]en el edificio principal del santuario[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_NAOT]
[f 0 5 -258][f 2 1]> Ahora que caes, todavía[n]no te has despedido de Naoto.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Naoto siempre andaba por[n][f 0 1 2]el pasillo de la primera planta[n]del edificio de aulas[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_ROUH]
[f 0 5 -258][f 2 1]> Ahora que caigo, ¿qué habrá sido[n]de Hisano?[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Deberías ir al lugar[n]donde pasaste tiempo con ella.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Hisano estaba siempre en la[n][f 0 1 2]ribera[n]del lecho del río Samegawa[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_HAHA]
[f 0 5 -258][f 2 1]> Ahora que caes, todavía[n]no te has despedido de Eri.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Deberías ir a la colina[n]donde la conociste.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Para ir a la [f 0 1 2]colina, dirígete a la[n]parada de autobús de la calle comercial[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_NURS]
[f 0 5 -258][f 2 1]> Ahora que caigo, ¿qué habrá sido[n]de Sayoko?[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Deberías ir al lugar[n]donde pasaste tiempo con ella.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Para ir al [f 0 1 2]hospital municipal[n]de Inaba, dirígete a la parada de bus[n]de la calle comercial[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_DOUJ]
[f 0 5 -258][f 2 1]> Deberías despedirte de Dojima.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Deberías ir a la [f 0 1 2]residencia Dojima[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_NANA]
[f 0 5 -258][f 2 1]> Deberías saludar a Nanako.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Deberías ir a la [f 0 1 2]residencia Dojima[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_DOUJ2]
[f 0 5 -258][f 2 1]> Deberías saludar a Dojima y a Nanako.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Deberías ir a la [f 0 1 2]residencia Dojima[f 0 1 0].[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_AI]
[f 0 5 -258][f 2 1]> Ahora que caes, todavía[n]no te has despedido de Ai.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Ai siempre andaba por[n][f 0 1 2]el pasillo de la primera planta[n]del edificio de aulas[f 0 1 0].[n][f 1 1][e]
