[sel StreetNight]
[f 0 5 -258][f 2 1]Calle comercial[e]
[f 0 5 -258][f 2 1]Santuario[e]
[f 0 5 -258][f 2 1]Volver a casa[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[sel ShoppingDistrict]
[f 0 5 -258][f 2 1]Calle comercial, Sur[e]
[f 0 5 -258][f 2 1]Calle comercial, Norte[e]
[f 0 5 -258][f 2 1]Shiroku[e]
[f 0 5 -258][f 2 1]Habitación Terciopelo[e]
[f 0 5 -258][f 2 1]Cancelar[e]

[msg MSG_MARIE_VELVET_IN [Marie]]
[f 0 5 -258][f 2 1][f 4 6 60 1 0 1]¿Vas a entrar? Yo también voy.[n][f 1 1][e]

[msg MARGARET_GOJITUDAN_01 [Margaret]]
[f 0 5 -258][f 2 1][f 4 6 34 1 0 1]Ah... Hola.[n][f 1 1][e]

[msg MSG_0320_AFTER_E428002]
[f 0 5 -258][f 2 1]> Ha empezado a llover.[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED]
[f 0 5 -258][f 2 1]> No tienes ninguna razón[n]para estar aquí.[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO]
[f 0 5 -258][f 2 1]> Tienes la sensación de que no has[n]acabado de despedirte de todo el mundo.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> ¿Quieres volver a casa y[n]prepararte para mañana?[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL]
[f 0 5 -258][f 2 1]> Tienes la sensación de que no te has[n]despedido de todos tus seres queridos.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> ¿Quieres volver a casa y[n]prepararte para mañana?[n][f 1 1][e]

[msg MSG_0320_RETURN_HOME]
[f 0 5 -258][f 2 1]> ¿Quieres volver a casa y[n]prepararte para mañana?[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO2]
[f 0 5 -258][f 2 1]> No tienes ninguna razón[n]para estar aquí.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Aún no has hablado con algunos de[n]tus seres queridos.[n][f 1 1][e]


[msg MSG_0320_RETURN_HOME2]
[f 0 5 -258][f 2 1]> No tienes ninguna razón[n]para estar aquí.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Es hora de volver a casa y[n]prepararse para mañana...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL3]
[f 0 5 -258][f 2 1]> No tienes ninguna razón[n]para estar aquí.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Ahora has dicho adiós a todos[n]tus seres queridos.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> ¿Hay algo más que aún[n]tengas que hacer aquí...?[n][f 1 1][e]

[msg MSG_0417_VELVET_DONOTENT]
[f 0 5 -258][f 2 1]> No necesitas entrar aquí...[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED3]
[f 0 5 -258][f 2 1]> No hay razón para que estés aquí...[n][f 1 1][e]

[msg MSG_0320_DOUJIMA_SEARCH]
[f 0 5 -258][f 2 1]> Deberías buscar a Dojima y Nanako.[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL2]
[f 0 5 -258][f 2 1]> No deberías tener razón para venir[n]aquí...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Ahora has dicho adiós a todos[n]tus seres queridos.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Es hora de volver a casa y[n]prepararse para mañana...[n][f 1 1][e]
